### ISSUE TITLE
Fail to decrypt when sign message

### ISSUE THREAD

**Issue by ngocan3897** [WalletConnect/react-native-examples#54]
my react native dApp example got error: fail to decrypt when trying to get sign message from other wallet (example: trust wallet , ....) in the same device

Tested Device: 
iphone 12 ios 16.0
iphone 11 ios 16.1.2

<img width="787" alt="Screen Shot 2023-05-11 at 10 20 22" src="https://github.com/WalletConnect/react-native-examples/assets/39030026/751e33b6-d305-49f8-acbb-422a7aa939d4">

**Comment by dshym** [comment]
The same issue on my side. But with UniversalProvider and Ethers implementation. 

**Environment:**
- iPhone 12, iOS 16.3.1
- Xcode 14.0.1 and 14.0.3
- Node 16 and 18
- "react-native": "0.71.2"
- "@walletconnect/react-native-compat": "^2.5.1"
- "@walletconnect/universal-provider": "^2.5.1"
- "@ethersproject/shims": "5.6.0"
- "ethers": "5.6.9"

```
Possible Unhandled Promise Rejection (id: 1):
Error: Failed to decrypt
Error: Failed to decrypt
    at Cn (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:201036:36)
    at ?anon_0_ (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:207326:80)
    at next (native)
    at asyncGeneratorStep (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:20416:26)
    at _next (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:20435:29)
    at anonymous (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:20440:14)
    at tryCallTwo (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:20432:25)
    at apply (native)
    at anonymous (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:207333:30)
    at ?anon_0_ (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:199531:59)
    at next (native)
    at asyncGeneratorStep (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:20416:26)
    at _next (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:20435:29)
    at anonymous (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:20440:14)
    at tryCallTwo (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:20432:25)
    at apply (native)
    at anonymous (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:199541:32)
    at apply (native)
    at emit (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:199992:49)
    at ?anon_0_ (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:208501:72)
    at next (native)
    at asyncGeneratorStep (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:20416:26)
    at _next (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:20435:29)
    at tryCallOne (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/distiller/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:25946:26)
    at _callTimer (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:25865:17)
    at _callReactNativeMicrotasksPass (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:25895:17)
    at callReactNativeMicrotasks (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:26058:44)
    at __callReactNativeMicrotasks (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:2410:46)
    at anonymous (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:2222:45)
    at __guard (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:2394:15)
    at flushedQueue (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:2221:21)
    at callFunctionReturnFlushedQueue (http://192.168.8.101:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.v2Explorer:2206:33)
```

Looks like error comes from here:
```
function Cn(e) {
    var n = new (_$$_REQUIRE(_dependencyMap[8], "@stablelib/chacha20poly1305").ChaCha20Poly1305)(_$$_REQUIRE(_dependencyMap[4], "uint8arrays").fromString(e.symKey, f)),
      _Z = Z(e.encoded),
      t = _Z.sealed,
      r = _Z.iv,
      s = n.open(r, t);
    if (s === null) throw new Error("Failed to decrypt");
    return _$$_REQUIRE(_dependencyMap[4], "uint8arrays").toString(s, q);
  }
```

WalletConnect libraries versions downgrading and upgrading didn't help.

**Comment by Mostafatalaat770** [comment]
This is fixed in the latest version of trust wallet, you can close the issue now!

**Comment by ignaciosantise** [comment]
As @Mostafatalaat770 said, this issue is solved in Trust Wallet v8.9.
